---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerhack-business
spec:
  selector:
    matchLabels:
      app: careerhack-business
  replicas: 2
  template:
    metadata:
      labels:
        app: careerhack-business
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
                - node4
                - node5
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node4
                - node5
      containers:
      - name: careerhack-business
        image: le3721/careerhack-business:latest
        imagePullPolicy: Always
        command: ["python3","app/main.py"]
        env:
        - name: WEB_PORT
          value: "8100"
        - name: INVENTORY_URL
          value: "http://careerhack-inventory:8200/api"
        - name: STORAGE_URL
          value: "http://careerhack-storage:8300/api"
        ports:
        - containerPort: 8100
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8100
          initialDelaySeconds: 10
          periodSeconds: 1
          failureThreshold: 4
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerhack-inventory
spec:
  selector:
    matchLabels:
      app: careerhack-inventory
  replicas: 1
  template:
    metadata:
      labels:
        app: careerhack-inventory
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node2
                - node4
                - node5
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node2
      containers:
      - name: careerhack-inventory
        image: le3721/careerhack-inventory:latest
        imagePullPolicy: Always
        command: ["python3","app/main.py"]
        env:
        - name: WEB_PORT
          value: "8200"
        ports:
        - containerPort: 8200
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8200
          initialDelaySeconds: 10
          periodSeconds: 1
          failureThreshold: 4
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerhack-storage
spec:
  selector:
    matchLabels:
      app: careerhack-storage
  replicas: 1
  template:
    metadata:
      labels:
        app: careerhack-storage
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node3
                - node4
                - node5
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node3
      containers:
      - name: careerhack-storage
        image: le3721/careerhack-storage:latest
        imagePullPolicy: Always
        command: ["python3","app/main.py"]
        env:
        - name: WEB_PORT
          value: "8300"
        ports:
        - containerPort: 8300
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8300
          initialDelaySeconds: 10
          periodSeconds: 1
          failureThreshold: 4
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: careerhack-business
spec:
  type: NodePort
  selector:
    app: careerhack-business
  ports:
    - protocol: TCP
      name: business
      targetPort: 8100
      port: 8100
      nodePort: 30770
---
apiVersion: v1
kind: Service
metadata:
  name: careerhack-inventory
spec:
  selector:
    app: careerhack-inventory
  ports:
    - protocol: TCP
      name: inventory
      targetPort: 8200
      port: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: careerhack-storage
spec:
  selector:
    app: careerhack-storage
  ports:
    - protocol: TCP
      name: storage
      targetPort: 8300
      port: 8300